### ISSUE TITLE
What is it good for?

### ISSUE THREAD

**Issue by grssnbchr** [pudo/nomenklatura#50]
Pudo, I don't (yet) get the sense behind this service. So users can store canonical names of entities and their aliases in the cloud. What advantage does this provide over storage in a local database, for example? 

I suppose (but I am not sure because it's not documented) that if I want to re-conciliate an entity (e.g. I have many aliases but their not yet mapped to an entity) I can use the already existing datasets of ALL users to map my own aliases (because somebody has already done that?). If yes, maybe you should add some documentation. But maybe I'm just too stupid :-)

**Comment by pudo** [comment]
No it's a bit abstract, I'll admit that :) Some places to look at that may make some sense: 

* @robbi5's [deployment for kleine-anfragen.de](http://nk.kleine-anfragen.de).
* The [DESIGN](https://github.com/pudo/nomenklatura/blob/master/DESIGN.md) document.
* The actual documentation, particularly [getting started](https://github.com/pudo/nomenklatura/blob/master/nomenklatura/static/templates/docs/gettingstarted.html). 

It's worth pointing out that I don't intend this as a collaborative cloud tool very much, I think most use cases are for integrating one particular set of entities from one particular source. So the advantage of running a (local or public) server (rather than doing it in some database) is a) you get a well-defined process, b) you get a UI for making choices.

So if you're trying to merge multiple datasets, what other strategies do you usually apply?

**Comment by grssnbchr** [comment]
Oh, that's the first time I see these pages (Design and getting started). Maybe you should link more prominently to those on the home page (http://nomenklatura.okfnlabs.org/) or under http://nomenklatura.okfnlabs.org/about?

**Comment by pudo** [comment]
Hi! I'm resetting this project to work off of other tooling I've worked on for the last few years. Check out the README for details. Closing all issues as they won't pertain to the new codebase.
